import { Button, VerticalBox , HorizontalBox, ListView} from "std-widgets.slint";

export struct file_info {
    locked: bool,
    file_name: string,
    file_ver: string,
    note: string,
    note_vis: bool,
}

component SlideOver inherits Rectangle {
    in property<string> info: "test string";
    visible: false;
    VerticalLayout {
        Rectangle {
            Text {
                text: info;
                vertical-alignment: center;
                font-weight: 900;
                horizontal-stretch: 1;
                font-size: 10pt;
            }
        }
        Rectangle {
            height: 2%;
            width: 100%;
            background: yellow;
        }
    }
}

component FileInfo inherits HorizontalLayout {

    in-out property<file_info> info :  {
        locked: true,
        file-name: "My File.mer",
        file-ver: "12.0",
        note: "test",
        note_vis: false,
    };

    property<color> icon-color: info.locked ? #ff4343 : #107c10;

    callback unlock(string);
    callback slide-over();

    padding: 5px;
    height: 50px;

    Rectangle {
        border-width: 1px;
        inf-so := SlideOver {
            info: root.info.note;
            visible: info.note-vis;
            states [
                vis when self.visible : {
                    x: 0px;
                }
                not-vis when !self.visible : {
                    x: root.width * -1;
                }
            ]

            animate x {
                duration: 1000ms;
                easing: ease-in-out;
            }
        }
        HorizontalBox {
            lbl := Text {
                text: "\{info.file_name}: (v\{info.file_ver})";
                vertical-alignment: center;
                font-weight: 900;
                horizontal-stretch: 1;
                font-size: 10pt;
            }
            info-icon := Image {
                //this circle question icon is a temporary one while I'm offline, I just had it on my machine
                source: @image-url("../assets/icons/circle-question.svg");
                colorize: yellow;
                height: 100%;
                width: self.height;
                visible: info.note != "";
                info-ta := TouchArea {
                    clicked => {
                        slide-over();
                    }
                }
            }
            icon := Image {
                source: info.locked ? @image-url("../assets/icons/protected.svg") : @image-url("../assets/icons/unlocked.svg");
                colorize: icon-color;
                height: 100%;
                width: self.height;
                //y: 1px;
                horizontal-stretch: 0;

                icn-ta := TouchArea {
                    clicked => {
                        if (info.locked) {
                            unlock(info.file-name)
                        }
                    }
                }

                states [
                    clicked when icn-ta.pressed && info.locked: {
                        colorize: icon-color.darker(0.4);
                    }
                    hvr when icn-ta.has-hover && info.locked : {
                        colorize: icon-color.brighter(0.4);
                    }
                    not-hvr when !icn-ta.has-hover : {
                        colorize: icon-color;
                    }
                ]
            }

            states [
                vis when !inf-so.visible : {
                    x: 0px;
                }
                not-vis when inf-so.visible : {
                    x: root.width;
                }
            ]

            animate x {
                duration: 1000ms;
                easing: ease-in-out;
            }
        }
    }
}

export component AppWindow inherits Window {
    min-height: 320px;
    min-width: 480px;
    icon: @image-url("../assets/icons/logo.png");
    in property<[file_info]> files;

    callback unlock(string, int);
    callback select_files();
    callback slide_over(int);

    vl := VerticalLayout {
        ListView {
            for f_info[idx] in files : FileInfo {
                info: f_info;
                unlock => { unlock(f_info.file_name, idx); }
                slide-over => { slide-over(idx); }
            }
        }
        Button {
            text: "Select Files";
            clicked => { select_files(); }
        }
    }
}